name: Build and Release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:
    inputs:
      trigger:
        description: 'Trigger the workflow manually'
        required: true
      tag:
        description: 'Tag to use (only applicable when manually triggered)'
        required: true

jobs:
  build:
    name: Build for multiple platforms
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build for Linux
        run: cargo build --release --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: '-C link-arg=-s'

      - name: Build for macOS
        run: cargo build --release --target x86_64-apple-darwin
        env:
          RUSTFLAGS: '-C link-arg=-Wl,-dead_strip'

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-gnu
        env:
          RUSTFLAGS: '-C link-arg=-s'

  release:
    needs: build
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine Tag Reference
        id: tag_ref
        run: echo "::set-output name=tag_ref::${{ github.event.inputs.trigger || inputs.tag }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag_ref.outputs.tag_ref }}
          release_name: Release ${{ steps.tag_ref.outputs.tag_ref }}
          draft: false
          prerelease: false

      - name: Upload Linux binary
        uses: actions/upload-artifact@v2
        with:
          name: linux-binary
          path: target/x86_64-unknown-linux-gnu/release/agl

      - name: Upload macOS binary
        uses: actions/upload-artifact@v2
        with:
          name: mac-binary
          path: target/x86_64-apple-darwin/release/agl

      - name: Upload Windows binary
        uses: actions/upload-artifact@v2
        with:
          name: windows-binary
          path: target/x86_64-pc-windows-gnu/release/agl.exe
